import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/Navbar";
import { GridBackgroundDemo } from "@/components/GirdBackground";
import { DotBackgroundDemo } from "@/components/DotBackground";
import { SmallGridBackgroundDemo } from "@/components/GridSmallBackground";
import { CanvasRevealEffectDemo } from "@/components/CanvasRevealEffectDemo";
import { CanvasRevealEffectDemo3 } from "@/components/CanvasRevealEffectDemo3";
import { CanvasRevealEffectDemo2 } from "@/components/CanvasRevealEffectDemo2";
import { ThreeDCardDemo } from "@/components/ThreeDCardDemo";
import { LampDemo } from "@/components/LampDemo";
import { SignupFormDemo } from "@/components/SignupFormDemo";
import { InfiniteMovingCardsDemo } from "@/components/InfiniteMovingCardsDemo";
import { SpotlightPreview } from "@/components/SpotlightPreview";
import { TypewriterEffectSmoothDemo } from "@/components/TypewriterEffectSmoothDemo";
import { TypewriterEffectDemo } from "@/components/TypewriterEffectDemo";
import { TextRevealCard } from "@/components/ui/text-reveal-card";
import { TextRevealCardPreview } from "@/components/TextRevealCardPreview";
import { TextGenerateEffectDemo } from "@/components/TextGenerateEffectDemo";
import { StickyScrollRevealDemo } from "@/components/StickyScrollRevealDemo";
import { SparklesPreview } from "@/components/SparklesPreview";
import { SparklesPreviewFull } from "@/components/SparklesPreviewFull";
import { AnimatedTooltipPreview } from "@/components/AnimatedTooltipPreview";
import { BackgroundBoxesDemo } from "@/components/BackgroundBoxesDemo";
import { DirectionAwareHoverDemo } from "@/components/DirectionAwareHoverDemo";
import { MeteorsDemo } from "@/components/MeteorsDemo";
import { TabsDemo } from "@/components/TabsDemo";
import { MultiStepLoaderDemo } from "@/components/MultiStepLoaderDemo";
import { CardStackDemo } from "@/components/CardStackDemo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <NavbarDemo />
        </div>
        <div className="">
          <GridBackgroundDemo />
        </div>
        <div className="">
          <DotBackgroundDemo />
        </div>
        <div className="">
          <SmallGridBackgroundDemo />
        </div>
        <div className="">
          <CanvasRevealEffectDemo />
        </div>
        <div className="">
          <CanvasRevealEffectDemo3 />
        </div>
        <div className="">
          <CanvasRevealEffectDemo2 />
        </div>
        <div className="">
          <ThreeDCardDemo />
        </div>
        <div className="">
          <LampDemo />
        </div>
        <div className="">
          <SignupFormDemo />
        </div>
        <div className="">
          <InfiniteMovingCardsDemo />
        </div>
        <div className="">
          <SpotlightPreview />
        </div>
        <div className="">
          <TypewriterEffectSmoothDemo />
        </div>
        <div className="">
          <TypewriterEffectDemo />
        </div>
        <div className="">
          <TextRevealCardPreview />
        </div>
        <div className="h-screen flex flex-col justify-center items-center">
          <div className="w-1/2">
            <TextGenerateEffectDemo />
          </div>
        </div>
        <div className="">
          <StickyScrollRevealDemo />
        </div>
        <div className="">
          <SparklesPreview />
        </div>
        <div className="">
          <SparklesPreviewFull />
        </div>
        <div className="flex h-screen justify-center items-center">
          <AnimatedTooltipPreview />
        </div>
        <div className="flex h-screen justify-center items-center">
          <BackgroundBoxesDemo />
        </div>
        <div className="">
          <DirectionAwareHoverDemo />
        </div>
        <div className="h-screen flex justify-center items-center">
          <MeteorsDemo />
        </div>
        <div className="">
          <TabsDemo />
        </div>
        <div className="flex justify-center items-center h-screen">
          <MultiStepLoaderDemo />
        </div>
        <div className="">
          <CardStackDemo />
        </div>
      </body>
    </html>
  );
}
